/*
 * pidgin4: system idle time from the Wayland ext-idle-notify-v1 protocol.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * See pidginidle-wayland.h. The client code is generated by wayland-scanner
 * from wayland-protocols' staging/ext-idle-notify/ext-idle-notify-v1.xml
 * (meson.build).
 */
#include <string.h>

#include <gtk/gtk.h>
#ifdef GDK_WINDOWING_WAYLAND
#include <gdk/wayland/gdkwayland.h>
#endif
#include <wayland-client.h>

#include "ext-idle-notify-v1-client-protocol.h"

#include "pidginidle-wayland.h"

static struct ext_idle_notifier_v1 *notifier = NULL;
static struct ext_idle_notification_v1 *notification = NULL;
static struct wl_display *display = NULL;
static struct wl_event_queue *queue = NULL;
static GSource *queue_source = NULL;
static guint notifier_version = 0;
static guint idle_timeout = 60;
static gint64 idled_at = 0;
static void (*changed_cb)(gboolean idle) = NULL;

time_t
pidgin_idle_time_since(gint64 now, gint64 idled_at_us, guint timeout)
{
	gint64 idle;

	if (idled_at_us <= 0)
		return 0;

	/* The user was last active @timeout seconds before "idled". */
	idle = (now - idled_at_us) / G_USEC_PER_SEC + timeout;
	return idle > 0 ? (time_t)idle : 0;
}

time_t
pidgin_idle_wayland_get_time_idle(void)
{
	return pidgin_idle_time_since(g_get_real_time(), idled_at, idle_timeout);
}

void
pidgin_idle_wayland_set_callback(void (*callback)(gboolean idle))
{
	changed_cb = callback;
}

static void
notification_idled(void *data, struct ext_idle_notification_v1 *n)
{
	idled_at = g_get_real_time();
	if (changed_cb != NULL)
		changed_cb(TRUE);
}

static void
notification_resumed(void *data, struct ext_idle_notification_v1 *n)
{
	if (changed_cb != NULL)
		changed_cb(FALSE);
	idled_at = 0;
}

static const struct ext_idle_notification_v1_listener notification_listener = {
	notification_idled,
	notification_resumed,
};

static void
registry_global(void *data, struct wl_registry *registry, uint32_t name,
                const char *interface, uint32_t version)
{
	if (notifier == NULL &&
	    strcmp(interface, ext_idle_notifier_v1_interface.name) == 0) {
		notifier_version = MIN(version, 2);
		notifier = wl_registry_bind(registry, name,
			&ext_idle_notifier_v1_interface, notifier_version);
	}
}

static void
registry_global_remove(void *data, struct wl_registry *registry, uint32_t name)
{
}

static const struct wl_registry_listener registry_listener = {
	registry_global,
	registry_global_remove,
};

/*
 * Dispatching our queue. GDK reads the display fd (distributing what it
 * reads to every queue) but dispatches only its own queue; tested with GTK
 * 4.22: proxies left on the default queue got their events only during
 * GDK's roundtrips at shutdown. So our proxies live on a private queue and
 * this source dispatches it.
 *
 * The source never reads the fd itself: a second reader in the same thread
 * would deadlock in wl_display_read_events() while GDK is prepared to
 * read. prepare() only asks whether the queue has events
 * (wl_display_prepare_read_queue() fails then) and cancels the read at
 * once otherwise. After GDK's source has read new events, the main loop's
 * next iteration runs prepare() again and dispatches them.
 */
static gboolean
queue_prepare(GSource *source, gint *timeout)
{
	*timeout = -1;
	if (display == NULL || queue == NULL)
		return FALSE;
	if (wl_display_prepare_read_queue(display, queue) != 0)
		return TRUE; /* events are queued */
	wl_display_cancel_read(display);
	return FALSE;
}

static gboolean
queue_check(GSource *source)
{
	return FALSE;
}

static gboolean
queue_dispatch(GSource *source, GSourceFunc callback, gpointer data)
{
	if (display != NULL && queue != NULL)
		wl_display_dispatch_queue_pending(display, queue);
	return G_SOURCE_CONTINUE;
}

static GSourceFuncs queue_source_funcs = {
	queue_prepare,
	queue_check,
	queue_dispatch,
	NULL,
	NULL,
	NULL
};

/*
 * PIDGIN4_IDLE_DEBUG: every 5 s a wl_display.sync on our queue, and the
 * time until its "done" is dispatched. Shows that the queue is dispatched
 * promptly (the idle events themselves need the user to stop typing).
 */
static guint debug_timer = 0;

static void
debug_sync_done(void *data, struct wl_callback *callback, uint32_t serial)
{
	gint64 *sent = data;

	g_message("idle: debug: our queue dispatched a sync after %" G_GINT64_FORMAT
	          " µs (idle now %ld s)", g_get_monotonic_time() - *sent,
	          (long)pidgin_idle_wayland_get_time_idle());
	g_free(sent);
	wl_callback_destroy(callback);
}

static const struct wl_callback_listener debug_sync_listener = {
	debug_sync_done,
};

static gboolean
debug_sync_cb(gpointer data)
{
	struct wl_display *wrapper;
	struct wl_callback *callback;
	gint64 *sent;

	if (display == NULL || queue == NULL) {
		debug_timer = 0;
		return G_SOURCE_REMOVE;
	}

	wrapper = wl_proxy_create_wrapper(display);
	wl_proxy_set_queue((struct wl_proxy *)wrapper, queue);
	callback = wl_display_sync(wrapper);
	wl_proxy_wrapper_destroy(wrapper);
	sent = g_new(gint64, 1);
	*sent = g_get_monotonic_time();
	wl_callback_add_listener(callback, &debug_sync_listener, sent);
	wl_display_flush(display);
	return G_SOURCE_CONTINUE;
}

gboolean
pidgin_idle_wayland_start(guint timeout)
{
#ifdef GDK_WINDOWING_WAYLAND
	GdkDisplay *gdk_display = gdk_display_get_default();
	struct wl_display *wrapper;
	struct wl_registry *registry;
	struct wl_seat *seat;
	GdkSeat *gdk_seat;

	pidgin_idle_wayland_stop();

	if (gdk_display == NULL || !GDK_IS_WAYLAND_DISPLAY(gdk_display))
		return FALSE;

	gdk_seat = gdk_display_get_default_seat(gdk_display);
	if (gdk_seat == NULL)
		return FALSE;
	seat = gdk_wayland_seat_get_wl_seat(gdk_seat);

	display = gdk_wayland_display_get_wl_display(gdk_display);

	/* Everything of ours on a private queue: the registry roundtrip does
	 * not dispatch GTK's events, and the notification's events are ours
	 * to dispatch (see above). */
	queue = wl_display_create_queue(display);
	wrapper = wl_proxy_create_wrapper(display);
	wl_proxy_set_queue((struct wl_proxy *)wrapper, queue);
	registry = wl_display_get_registry(wrapper);
	wl_proxy_wrapper_destroy(wrapper);
	wl_registry_add_listener(registry, &registry_listener, NULL);
	wl_display_roundtrip_queue(display, queue);
	wl_registry_destroy(registry);

	if (notifier == NULL) {
		wl_event_queue_destroy(queue);
		queue = NULL;
		display = NULL;
		return FALSE;
	}

	idle_timeout = MAX(timeout, 1);
	idled_at = 0;
	/* The notification inherits the notifier's (our) queue. */
	if (notifier_version >= 2)
		notification = ext_idle_notifier_v1_get_input_idle_notification(
			notifier, idle_timeout * 1000, seat);
	else
		notification = ext_idle_notifier_v1_get_idle_notification(
			notifier, idle_timeout * 1000, seat);
	ext_idle_notification_v1_add_listener(notification, &notification_listener,
	                                      NULL);
	wl_display_flush(display);

	queue_source = g_source_new(&queue_source_funcs, sizeof(GSource));
	g_source_set_name(queue_source, "pidgin4 ext-idle-notify queue");
	g_source_set_priority(queue_source, G_PRIORITY_DEFAULT);
	g_source_attach(queue_source, NULL);

	if (g_getenv("PIDGIN4_IDLE_DEBUG") != NULL)
		debug_timer = g_timeout_add_seconds(5, debug_sync_cb, NULL);

	return TRUE;
#else
	return FALSE;
#endif
}

void
pidgin_idle_wayland_stop(void)
{
	if (debug_timer != 0) {
		g_source_remove(debug_timer);
		debug_timer = 0;
	}
	if (queue_source != NULL) {
		g_source_destroy(queue_source);
		g_source_unref(queue_source);
		queue_source = NULL;
	}
	if (notification != NULL) {
		ext_idle_notification_v1_destroy(notification);
		notification = NULL;
	}
	if (notifier != NULL) {
		ext_idle_notifier_v1_destroy(notifier);
		notifier = NULL;
	}
	if (display != NULL)
		wl_display_flush(display);
	if (queue != NULL) {
		wl_event_queue_destroy(queue);
		queue = NULL;
	}
	display = NULL;
	notifier_version = 0;
	idled_at = 0;
}

gboolean
pidgin_idle_wayland_is_running(void)
{
	return notification != NULL;
}

guint
pidgin_idle_wayland_get_version(void)
{
	return notification != NULL ? notifier_version : 0;
}
