#!/usr/bin/env bash
# run.sh: a two-instance pidgin4 test against a throwaway local Prosody.
#
# Starts a user-local Prosody 13 (c2s with carbons, MAM with the default
# archive policy "roster", smacks, CSI, PEP, blocking (bouncing blocked
# messages), a test module that advertises XEP-0377 reporting, a MUC with
# MAM and occupant-id, HTTP file share), creates the users
# alice@localhost and bob@localhost (subscribed to each other) and one
# room, writes two scratch
# profiles with just that one XMPP account each (the self-signed server
# certificate is pre-trusted in the profile), and starts two pidgin4
# instances signed in, each on its own private Xvfb and D-Bus session.
# Each instance loads ctl-plugin.c (built here against the prefix): lines
# written to $work/ctl-NAME are run as commands (see there and ctl in
# lib.sh), for libpurple API and prpl IPC that has no UI yet.
# Only these throwaway accounts are ever signed in; nothing touches
# ~/.purple, ~/.purple-gtk4 or the system.
#
# Usage:
#   run.sh start [NAME...]   # fresh server data and profiles, then the
#                            # instances (default: alice bob; "alice2" is
#                            # alice's second resource, for carbons)
#   run.sh server            # server only (users, room)
#   run.sh stop-instance NAME / start-instance NAME
#                            # restart one instance on its profile (MAM)
#   run.sh stop              # stop everything
#   drive.sh                 # the scripted UI scenario (see there)
#
# Environment:
#   PROSODY_PREFIX  Prosody 13 install prefix (bin/prosody; its Lua rocks
#                   luasocket, luasec, luaexpat, luafilesystem under
#                   share/lua/5.4 and lib/lua/5.4 if not system-wide)
#   PROSODY_PLUGINS optional extra plugin path (community modules)
#   PIDGIN4         pidgin4 binary (default ~/.local/pidgin4/bin/pidgin4)
#   XMPP_LIVE_DIR   work directory (default ${TMPDIR:-/tmp}/pidgin4-xmpp-live)
#   XMPP_LIVE_PORT  c2s port (default 25322; HTTP is port + 58)
#   XMPP_LIVE_KEEP  1: keep the server's data (archives, rooms) on start
set -euo pipefail

work=${XMPP_LIVE_DIR:-${TMPDIR:-/tmp}/pidgin4-xmpp-live}
port=${XMPP_LIVE_PORT:-25322}
http_port=$((port + 58))
pidgin4=${PIDGIN4:-$HOME/.local/pidgin4/bin/pidgin4}
prosody_prefix=${PROSODY_PREFIX:-}
password=pencil1234
users="alice bob"
room=test

case "$work" in
	"$HOME/.purple"*|/usr*|/) echo "refusing work dir $work" >&2; exit 2 ;;
esac

prosody_env() {
	if [ -n "$prosody_prefix" ]; then
		export LUA_PATH="$prosody_prefix/share/lua/5.4/?.lua;$prosody_prefix/share/lua/5.4/?/init.lua;;"
		export LUA_CPATH="$prosody_prefix/lib/lua/5.4/?.so;;"
		prosody_bin=$prosody_prefix/bin/prosody
	else
		prosody_bin=$(command -v prosody)
	fi
}

write_config() {
	local srv=$work/prosody
	mkdir -p "$srv/data" "$srv/certs" "$srv/modules"
	# XEP-0377 is only a disco feature (the report rides in the XEP-0191
	# <block/>, which mod_blocklist handles); log the reports we get.
	cat > "$srv/modules/mod_xmpplive_reporting.lua" <<'LUA'
module:add_feature("urn:xmpp:reporting:1");
module:hook("iq-set/self/urn:xmpp:blocking:block", function (event)
	local item = event.stanza.tags[1]:get_child("item");
	local report = item and item:get_child("report", "urn:xmpp:reporting:1");
	if report then
		module:log("info", "XEP-0377 report on %s: %s", item.attr.jid, report.attr.reason);
	end
end, 10);
LUA
	if [ ! -s "$srv/certs/localhost.crt" ]; then
		openssl req -x509 -newkey rsa:2048 -nodes -days 365 -subj /CN=localhost \
			-addext "subjectAltName=DNS:localhost,DNS:conference.localhost,DNS:upload.localhost" \
			-keyout "$srv/certs/localhost.key" -out "$srv/certs/localhost.crt" 2>/dev/null
	fi
	cat > "$srv/prosody.cfg.lua" <<EOF
-- Generated by scripts/tests/xmpp-live/run.sh
plugin_paths = { "$srv/modules"; ${PROSODY_PLUGINS:+"$PROSODY_PLUGINS"} }
pidfile = "$srv/prosody.pid"
data_path = "$srv/data"
daemonize = true
prosodyctl_service_warnings = false
log = { { levels = { min = "debug" }; to = "file"; filename = "$srv/prosody.log" } }
authentication = "internal_hashed"
password_hash = "SHA-256"
c2s_ports = { $port }
c2s_direct_tls_ports = { }
c2s_interfaces = { "127.0.0.1" }
c2s_require_encryption = true
s2s_ports = { }
http_ports = { $http_port }
http_interfaces = { "127.0.0.1" }
https_ports = { }
http_external_url = "http://127.0.0.1:$http_port/"
-- the upload URLs name 127.0.0.1, not upload.localhost
http_default_host = "upload.localhost"
modules_enabled = {
	"roster"; "saslauth"; "tls"; "disco"; "carbons"; "smacks"; "csi";
	"csi_simple"; "ping"; "presence"; "vcard4"; "vcard_legacy"; "mam";
	"pep"; "bookmarks"; "private"; "blocklist"; "http";
	"xmpplive_reporting";
}
modules_disabled = { "s2s" }
archive_expires_after = "1d"
-- pidgin4 sets its own default to "always" once (XEP-0313 prefs)
default_archive_policy = "roster"
bounce_blocked_messages = true
smacks_hibernation_time = 60
certificates = "$srv/certs"
ssl = { certificate = "$srv/certs/localhost.crt"; key = "$srv/certs/localhost.key" }

VirtualHost "localhost"
	ssl = { certificate = "$srv/certs/localhost.crt"; key = "$srv/certs/localhost.key" }

Component "conference.localhost" "muc"
	modules_enabled = { "muc_mam" }
	muc_room_default_persistent = true
	muc_room_default_public = true
	muc_room_default_whois = "anyone"
	muc_room_locking = false
	restrict_room_creation = false

Component "upload.localhost" "http_file_share"
	http_file_share_size_limit = 10485760
EOF
}

add_users() {
	local srv=$work/prosody src
	src=$(dirname "$(dirname "$prosody_bin")")/lib/prosody
	cat > "$srv/adduser.lua" <<EOF
package.path = "$src/?.lua;" .. package.path
package.cpath = "$src/?.so;" .. package.cpath
CFG_SOURCEDIR = "$src"
CFG_PLUGINDIR = "$src/modules/"
if pcall(dofile, "$src/loader.lua") then package.loaded["prosody.loader"] = true end
arg = { "--config", "$srv/prosody.cfg.lua" }
require "prosody.util.startup".prosodyctl()
local um = require "prosody.core.usermanager"
require "prosody.core.storagemanager".initialize_host("localhost")
um.initialize_host("localhost")
local users = { $(for u in $users; do printf '"%s", ' "$u"; done) }
for _, u in ipairs(users) do
	if not um.user_exists(u, "localhost") then
		assert(um.create_user(u, "$password", "localhost"))
	end
end
-- everyone has everyone else in the roster, subscribed both ways
-- (presence: XEP-0319 idle, invisibility)
local rm = require "prosody.core.rostermanager"
for _, u in ipairs(users) do
	local roster = { [false] = { version = 1, pending = {} } }
	for _, o in ipairs(users) do
		if o ~= u then
			roster[o .. "@localhost"] = { subscription = "both", groups = { Buddies = true } }
		end
	end
	assert(rm.save_roster(u, "localhost", roster))
end
EOF
	lua5.4 "$srv/adduser.lua"
}

start_server() {
	prosody_env
	write_config
	if [ -s "$work/prosody/prosody.pid" ] && kill -0 "$(cat "$work/prosody/prosody.pid")" 2>/dev/null; then
		echo "prosody already running"
	else
		add_users
		"$prosody_bin" --config "$work/prosody/prosody.cfg.lua" -D
		for _ in $(seq 40); do
			[ -s "$work/prosody/prosody.pid" ] && ss -ltn | grep -q "127.0.0.1:$port " && break
			sleep 0.25
		done
		ss -ltn | grep -q "127.0.0.1:$port " || { echo "prosody did not start; see $work/prosody/prosody.log" >&2; exit 1; }
	fi
	echo "prosody on 127.0.0.1:$port (HTTP $http_port), users: $users (password $password), room $room@conference.localhost"
}

# build_ctl_plugin OUT: the test control plugin, against the prefix that
# pidgin4 runs with
build_ctl_plugin() {
	local prefix
	prefix=$(dirname "$(dirname "$(readlink -f "$pidgin4")")")
	PKG_CONFIG_PATH=$prefix/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH} \
	gcc -shared -fPIC -Wall -Wno-deprecated-declarations -o "$1" \
		"$(dirname "$0")/ctl-plugin.c" $(PKG_CONFIG_PATH=$prefix/lib/pkgconfig pkg-config --cflags --libs purple)
}

# write_profile NAME: alice, bob, or alice2 (alice@localhost/second)
write_profile() {
	local name=$1 prof=$work/profile-$1 user other resource=pidgin4
	case "$name" in
		alice) user=alice other=bob ;;
		bob) user=bob other=alice ;;
		alice2) user=alice other=bob resource=second ;;
		*) echo "unknown instance $name" >&2; exit 2 ;;
	esac
	rm -rf "$prof"
	mkdir -p "$prof/certificates/x509/tls_peers" "$prof/pidgin4/plugins"
	build_ctl_plugin "$prof/pidgin4/plugins/xmpplive-ctl.so"
	cat > "$prof/prefs.xml" <<EOF
<?xml version='1.0' encoding='UTF-8' ?>

<pref version='1' name='/'>
	<pref name='pidgin4'>
		<pref name='plugins'>
			<pref name='loaded' type='pathlist'>
				<item value='$prof/pidgin4/plugins/xmpplive-ctl.so'/>
			</pref>
		</pref>
	</pref>
</pref>
EOF
	# Trusted as a cached peer certificate for the connect server
	# (x509_tls_cached verifies against connect_server, not the domain).
	cp "$work/prosody/certs/localhost.crt" "$prof/certificates/x509/tls_peers/127.0.0.1"
	cat > "$prof/accounts.xml" <<EOF
<?xml version='1.0' encoding='UTF-8' ?>

<account version='1.0'>
	<account>
		<protocol>prpl-jabber</protocol>
		<name>$user@localhost/$resource</name>
		<password>$password</password>
		<settings>
			<setting name='connect_server' type='string'>127.0.0.1</setting>
			<setting name='port' type='int'>$port</setting>
			<setting name='connection_security' type='string'>require_tls</setting>
			<setting name='ft_proxies' type='string'></setting>
		</settings>
		<settings ui='gtk-gaim'>
			<setting name='auto-login' type='bool'>1</setting>
		</settings>
		<current_error/>
	</account>
</account>
EOF
	cat > "$prof/blist.xml" <<EOF
<?xml version='1.0' encoding='UTF-8' ?>

<purple version='1.0'>
	<blist>
		<group name='Buddies'>
			<setting name='collapsed' type='bool'>0</setting>
			<contact>
				<buddy account='$user@localhost/$resource' proto='prpl-jabber'>
					<name>$other@localhost</name>
				</buddy>
			</contact>
			<chat proto='prpl-jabber' account='$user@localhost/$resource'>
				<component name='room'>$room</component>
				<component name='server'>conference.localhost</component>
				<component name='handle'>$user</component>
			</chat>
		</group>
	</blist>
	<privacy>
		<account proto='prpl-jabber' name='$user@localhost/$resource' mode='1'/>
	</privacy>
</purple>
EOF
}

start_instance() {
	local user=$1 prof=$work/profile-$1 fifo num
	fifo=$work/xvfb-$user.fd
	rm -f "$fifo"; mkfifo "$fifo"
	Xvfb -displayfd 3 -nolisten tcp -screen 0 1280x900x24 3<>"$fifo" >/dev/null 2>&1 &
	echo $! > "$work/xvfb-$user.pid"
	exec 4<>"$fifo"
	read -r -t 10 num <&4 || { echo "Xvfb did not start" >&2; exit 2; }
	exec 4<&-
	rm -f "$fifo"
	echo ":$num" > "$work/display-$user"
	(
		export DISPLAY=:$num GDK_BACKEND=x11 GTK_A11Y=none GSETTINGS_BACKEND=memory
		export XMPP_LIVE_CTL=$work/ctl-$user
		unset WAYLAND_DISPLAY
		exec dbus-run-session -- "$pidgin4" -m -d -c "$prof"
	) > "$work/pidgin4-$user.log" 2>&1 &
	echo $! > "$work/pidgin4-$user.pid"
	echo "pidgin4 ($user) on DISPLAY=:$num, log $work/pidgin4-$user.log"
}

stop_instance() {
	local name=$1 f pid
	f=$work/pidgin4-$name.pid
	if [ -e "$f" ]; then
		pid=$(cat "$f")
		pkill -TERM -P "$pid" 2>/dev/null || true
		for _ in $(seq 40); do kill -0 "$pid" 2>/dev/null || break; sleep 0.25; done
		kill "$pid" 2>/dev/null || true
		rm -f "$f"
	fi
	f=$work/xvfb-$name.pid
	if [ -e "$f" ]; then
		kill "$(cat "$f")" 2>/dev/null || true
		rm -f "$f"
	fi
}

stop_all() {
	local f name
	for f in "$work"/pidgin4-*.pid; do
		[ -e "$f" ] || continue
		name=${f##*/pidgin4-}
		stop_instance "${name%.pid}"
	done
	if [ -s "$work/prosody/prosody.pid" ]; then
		kill "$(cat "$work/prosody/prosody.pid")" 2>/dev/null || true
		rm -f "$work/prosody/prosody.pid"
	fi
	echo "stopped"
}

mkdir -p "$work"
case "${1:-start}" in
	server) start_server ;;
	start)
		shift
		[ -x "$pidgin4" ] || { echo "no pidgin4 at $pidgin4" >&2; exit 1; }
		stop_all >/dev/null
		[ "${XMPP_LIVE_KEEP:-}" = 1 ] || rm -rf "$work/prosody/data"
		start_server
		[ $# -gt 0 ] || set -- alice bob
		for name in "$@"; do
			write_profile "$name"
			start_instance "$name"
		done
		;;
	start-instance) start_instance "${2:?name}" ;;
	stop-instance) stop_instance "${2:?name}" ;;
	stop) stop_all ;;
	*) echo "usage: $0 start [NAME...]|server|start-instance NAME|stop-instance NAME|stop" >&2; exit 2 ;;
esac
